"""update tool

Revision ID: d138da34f3c1
Revises: e7f8a9b0c1d2
Create Date: 2025-12-08 06:08:56.176605

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
import sqlmodel # added


# revision identifiers, used by Alembic.
revision = 'd138da34f3c1'
down_revision = 'e7f8a9b0c1d2'
branch_labels = None
depends_on = None


def upgrade():
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm") 
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tool', sa.Column('llm_schema', sa.JSON(), nullable=True))
    op.add_column('tool', sa.Column('runtime_schema', sa.JSON(), nullable=True))
    op.add_column('tool', sa.Column('schema_version', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('tool', sa.Column('schema_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('tool', sa.Column('last_imported_at', sa.DateTime(), nullable=True))
    op.drop_index(op.f('uq_tool_module_function_user'), table_name='tool')
    op.create_unique_constraint('uq_tool_module_function_user', 'tool', ['module', 'function', 'user_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_tool_module_function_user', 'tool', type_='unique')
    op.create_index(op.f('uq_tool_module_function_user'), 'tool', ['module', 'function', 'user_id'], unique=True)
    op.drop_column('tool', 'last_imported_at')
    op.drop_column('tool', 'schema_hash')
    op.drop_column('tool', 'schema_version')
    op.drop_column('tool', 'runtime_schema')
    op.drop_column('tool', 'llm_schema')
    # ### end Alembic commands ###
