"""Initial migration

Revision ID: 99701a9b80f2
Revises: 
Create Date: 2025-11-17 07:31:20.523762

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
import sqlmodel # added
import geoalchemy2
from geoalchemy2 import Geography
from geoalchemy2.types import Geography as GeoAlchemyGeography

# revision identifiers, used by Alembic.
revision = '99701a9b80f2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm") 
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_sessions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_sessions_id'), 'chat_sessions', ['id'], unique=False)
    op.create_index(op.f('ix_chat_sessions_user_id'), 'chat_sessions', ['user_id'], unique=False)
    op.create_table('lakes',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('last_modified_by', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('visibility', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('lake_id', sa.Integer(), nullable=False),
    sa.Column('lake_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('location', geoalchemy2.types.Geography(geometry_type='POINT', srid=4326, from_text='ST_GeogFromText', name='geography'), nullable=True),
    sa.Column('lake_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('country', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('lake_id')
    )
    op.execute("DROP INDEX IF EXISTS idx_lakes_location;")
    op.create_index('idx_lakes_location', 'lakes', ['location'], unique=False, postgresql_using='gist')
    op.create_index(op.f('ix_lakes_lake_name'), 'lakes', ['lake_name'], unique=False)
    op.create_index(op.f('ix_lakes_organization_id'), 'lakes', ['organization_id'], unique=False)
    op.create_index(op.f('ix_lakes_user_id'), 'lakes', ['user_id'], unique=False)
    op.create_table('tooltype',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Enum('MCP', 'API', 'TOOL', name='tooltypeenum'), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tooltype_name'), 'tooltype', ['name'], unique=False)
    op.create_table('user',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('username', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('full_name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('hashed_password', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('role', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('organization', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('avatar_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_user_id'), 'user', ['id'], unique=False)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('chat_messages',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('role', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('content', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('tool_calls', sa.JSON(), nullable=True),
    sa.Column('tool_call_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('tool_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['chat_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_messages_id'), 'chat_messages', ['id'], unique=False)
    op.create_index(op.f('ix_chat_messages_session_id'), 'chat_messages', ['session_id'], unique=False)
    op.create_table('lake_area_time_series',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('last_modified_by', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('visibility', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lake_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('area', sa.Float(), nullable=False),
    sa.Column('source', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['lake_id'], ['lakes.lake_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('lake_id', 'timestamp')
    )
    op.create_index(op.f('ix_lake_area_time_series_lake_id'), 'lake_area_time_series', ['lake_id'], unique=False)
    op.create_index(op.f('ix_lake_area_time_series_organization_id'), 'lake_area_time_series', ['organization_id'], unique=False)
    op.create_index(op.f('ix_lake_area_time_series_timestamp'), 'lake_area_time_series', ['timestamp'], unique=False)
    op.create_index(op.f('ix_lake_area_time_series_user_id'), 'lake_area_time_series', ['user_id'], unique=False)
    op.create_table('lake_level_time_series',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('last_modified_by', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('visibility', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lake_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('water_level', sa.Float(), nullable=False),
    sa.Column('source', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['lake_id'], ['lakes.lake_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('lake_id', 'timestamp')
    )
    op.create_index(op.f('ix_lake_level_time_series_lake_id'), 'lake_level_time_series', ['lake_id'], unique=False)
    op.create_index(op.f('ix_lake_level_time_series_organization_id'), 'lake_level_time_series', ['organization_id'], unique=False)
    op.create_index(op.f('ix_lake_level_time_series_timestamp'), 'lake_level_time_series', ['timestamp'], unique=False)
    op.create_index(op.f('ix_lake_level_time_series_user_id'), 'lake_level_time_series', ['user_id'], unique=False)
    op.create_table('lake_volume_change_time_series',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('last_modified_by', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('visibility', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lake_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('water_volume', sa.Float(), nullable=False),
    sa.Column('source', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['lake_id'], ['lakes.lake_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('lake_id', 'timestamp')
    )
    op.create_index(op.f('ix_lake_volume_change_time_series_lake_id'), 'lake_volume_change_time_series', ['lake_id'], unique=False)
    op.create_index(op.f('ix_lake_volume_change_time_series_organization_id'), 'lake_volume_change_time_series', ['organization_id'], unique=False)
    op.create_index(op.f('ix_lake_volume_change_time_series_timestamp'), 'lake_volume_change_time_series', ['timestamp'], unique=False)
    op.create_index(op.f('ix_lake_volume_change_time_series_user_id'), 'lake_volume_change_time_series', ['user_id'], unique=False)
    op.create_table('lake_volume_time_series',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('last_modified_by', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('visibility', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lake_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('water_volume', sa.Float(), nullable=False),
    sa.Column('source', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['lake_id'], ['lakes.lake_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('lake_id', 'timestamp')
    )
    op.create_index(op.f('ix_lake_volume_time_series_lake_id'), 'lake_volume_time_series', ['lake_id'], unique=False)
    op.create_index(op.f('ix_lake_volume_time_series_organization_id'), 'lake_volume_time_series', ['organization_id'], unique=False)
    op.create_index(op.f('ix_lake_volume_time_series_timestamp'), 'lake_volume_time_series', ['timestamp'], unique=False)
    op.create_index(op.f('ix_lake_volume_time_series_user_id'), 'lake_volume_time_series', ['user_id'], unique=False)
    op.create_table('model',
    sa.Column('created_by_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('updated_by_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('provider', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('invoke_config', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['updated_by_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_model_id'), 'model', ['id'], unique=False)
    op.create_index(op.f('ix_model_name'), 'model', ['name'], unique=False)
    op.create_index(op.f('ix_model_user_id'), 'model', ['user_id'], unique=False)
    op.create_table('tool',
    sa.Column('created_by_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('updated_by_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('type', sa.Enum('MCP', 'API', 'TOOL', name='tooltypeenum'), nullable=False),
    sa.Column('scene', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('module', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('function', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('invoke_config', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['updated_by_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tool_id'), 'tool', ['id'], unique=False)
    op.create_index(op.f('ix_tool_name'), 'tool', ['name'], unique=False)
    op.create_index(op.f('ix_tool_type'), 'tool', ['type'], unique=False)
    op.create_index(op.f('ix_tool_user_id'), 'tool', ['user_id'], unique=False)
    op.create_table('agent',
    sa.Column('created_by_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('updated_by_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('scene', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('invoke_config', sa.JSON(), nullable=True),
    sa.Column('model_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('parent_agent_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('system_prompt', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['model_id'], ['model.id'], ),
    sa.ForeignKeyConstraint(['parent_agent_id'], ['agent.id'], ),
    sa.ForeignKeyConstraint(['updated_by_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_id'), 'agent', ['id'], unique=False)
    op.create_index(op.f('ix_agent_name'), 'agent', ['name'], unique=False)
    op.create_index(op.f('ix_agent_parent_agent_id'), 'agent', ['parent_agent_id'], unique=False)
    op.create_index(op.f('ix_agent_scene'), 'agent', ['scene'], unique=False)
    op.create_index(op.f('ix_agent_type'), 'agent', ['type'], unique=False)
    op.create_index(op.f('ix_agent_user_id'), 'agent', ['user_id'], unique=False)
    op.create_table('agenttoollink',
    sa.Column('agent_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('tool_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agent.id'], ),
    sa.ForeignKeyConstraint(['tool_id'], ['tool.id'], ),
    sa.PrimaryKeyConstraint('agent_id', 'tool_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('agenttoollink')
    op.drop_index(op.f('ix_agent_user_id'), table_name='agent')
    op.drop_index(op.f('ix_agent_type'), table_name='agent')
    op.drop_index(op.f('ix_agent_scene'), table_name='agent')
    op.drop_index(op.f('ix_agent_parent_agent_id'), table_name='agent')
    op.drop_index(op.f('ix_agent_name'), table_name='agent')
    op.drop_index(op.f('ix_agent_id'), table_name='agent')
    op.drop_table('agent')
    op.drop_index(op.f('ix_tool_user_id'), table_name='tool')
    op.drop_index(op.f('ix_tool_type'), table_name='tool')
    op.drop_index(op.f('ix_tool_name'), table_name='tool')
    op.drop_index(op.f('ix_tool_id'), table_name='tool')
    op.drop_table('tool')
    op.drop_index(op.f('ix_model_user_id'), table_name='model')
    op.drop_index(op.f('ix_model_name'), table_name='model')
    op.drop_index(op.f('ix_model_id'), table_name='model')
    op.drop_table('model')
    op.drop_index(op.f('ix_lake_volume_time_series_user_id'), table_name='lake_volume_time_series')
    op.drop_index(op.f('ix_lake_volume_time_series_timestamp'), table_name='lake_volume_time_series')
    op.drop_index(op.f('ix_lake_volume_time_series_organization_id'), table_name='lake_volume_time_series')
    op.drop_index(op.f('ix_lake_volume_time_series_lake_id'), table_name='lake_volume_time_series')
    op.drop_table('lake_volume_time_series')
    op.drop_index(op.f('ix_lake_volume_change_time_series_user_id'), table_name='lake_volume_change_time_series')
    op.drop_index(op.f('ix_lake_volume_change_time_series_timestamp'), table_name='lake_volume_change_time_series')
    op.drop_index(op.f('ix_lake_volume_change_time_series_organization_id'), table_name='lake_volume_change_time_series')
    op.drop_index(op.f('ix_lake_volume_change_time_series_lake_id'), table_name='lake_volume_change_time_series')
    op.drop_table('lake_volume_change_time_series')
    op.drop_index(op.f('ix_lake_level_time_series_user_id'), table_name='lake_level_time_series')
    op.drop_index(op.f('ix_lake_level_time_series_timestamp'), table_name='lake_level_time_series')
    op.drop_index(op.f('ix_lake_level_time_series_organization_id'), table_name='lake_level_time_series')
    op.drop_index(op.f('ix_lake_level_time_series_lake_id'), table_name='lake_level_time_series')
    op.drop_table('lake_level_time_series')
    op.drop_index(op.f('ix_lake_area_time_series_user_id'), table_name='lake_area_time_series')
    op.drop_index(op.f('ix_lake_area_time_series_timestamp'), table_name='lake_area_time_series')
    op.drop_index(op.f('ix_lake_area_time_series_organization_id'), table_name='lake_area_time_series')
    op.drop_index(op.f('ix_lake_area_time_series_lake_id'), table_name='lake_area_time_series')
    op.drop_table('lake_area_time_series')
    op.drop_index(op.f('ix_chat_messages_session_id'), table_name='chat_messages')
    op.drop_index(op.f('ix_chat_messages_id'), table_name='chat_messages')
    op.drop_table('chat_messages')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_id'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_tooltype_name'), table_name='tooltype')
    op.drop_table('tooltype')
    op.drop_index(op.f('ix_lakes_user_id'), table_name='lakes')
    op.drop_index(op.f('ix_lakes_organization_id'), table_name='lakes')
    op.drop_index(op.f('ix_lakes_lake_name'), table_name='lakes')
    op.drop_index('idx_lakes_location', table_name='lakes', postgresql_using='gist')
    op.drop_table('lakes')
    op.drop_index(op.f('ix_chat_sessions_user_id'), table_name='chat_sessions')
    op.drop_index(op.f('ix_chat_sessions_id'), table_name='chat_sessions')
    op.drop_table('chat_sessions')
    # ### end Alembic commands ###
