"""update tool

Revision ID: 1e0723fcbb1a
Revises: d138da34f3c1
Create Date: 2025-12-08 08:22:57.722766

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
import sqlmodel # added
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '1e0723fcbb1a'
down_revision = 'd138da34f3c1'
branch_labels = None
depends_on = None


def upgrade():
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm") 
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tool', sa.Column('tool_schema', sa.JSON(), nullable=True))
    op.add_column('tool', sa.Column('runtime_parameters', sa.JSON(), nullable=True))
    op.drop_column('tool', 'llm_schema')
    op.drop_column('tool', 'last_imported_at')
    op.drop_column('tool', 'runtime_schema')
    op.drop_column('tool', 'schema_version')
    op.drop_column('tool', 'schema_hash')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tool', sa.Column('schema_hash', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('tool', sa.Column('schema_version', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('tool', sa.Column('runtime_schema', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('tool', sa.Column('last_imported_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('tool', sa.Column('llm_schema', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_column('tool', 'runtime_parameters')
    op.drop_column('tool', 'tool_schema')
    # ### end Alembic commands ###
